# Generated by Django 6.0.3 on 2026-04-06 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('shareholders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_number', models.CharField(max_length=100, unique=True)),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True)),
                ('gift_status', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('STOPPED', 'Stopped')], default='ELIGIBLE', max_length=20)),
                ('stop_reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shares', to='masters.branch')),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='shareholders.shareholder')),
            ],
        ),
    ]
