# Generated by Django 6.0.3 on 2026-04-06 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.BigIntegerField()),
                ('action_type', models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('OTP_SENT', 'OTP Sent'), ('OTP_VERIFIED', 'OTP Verified'), ('SUBMIT_REQUEST', 'Submit Request'), ('ACCEPT_REQUEST', 'Accept Request'), ('REJECT_REQUEST', 'Reject Request'), ('SHIP_REQUEST', 'Ship Request'), ('DELIVER_REQUEST', 'Deliver Request'), ('UPLOAD_DOCUMENT', 'Upload Document'), ('DOWNLOAD_ACKNOWLEDGEMENT', 'Download Acknowledgement')], max_length=30)),
                ('changed_by_type', models.CharField(choices=[('SHAREHOLDER', 'Shareholder'), ('STAFF', 'Staff'), ('ADMIN', 'Admin'), ('SYSTEM', 'System')], max_length=20)),
                ('changed_by_id', models.BigIntegerField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='masters.branch')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=150)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='audit_logs.auditlog')),
            ],
        ),
    ]
