# Generated by Django 6.0.3 on 2026-04-06 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('shareholders', '0001_initial'),
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(max_length=100, unique=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('request_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=150, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=150, null=True)),
                ('acknowledgement_file_path', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_type', models.CharField(choices=[('SHAREHOLDER', 'Shareholder'), ('STAFF', 'Staff'), ('ADMIN', 'Admin'), ('SYSTEM', 'System')], default='SHAREHOLDER', max_length=20)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_type', models.CharField(blank=True, choices=[('SHAREHOLDER', 'Shareholder'), ('STAFF', 'Staff'), ('ADMIN', 'Admin'), ('SYSTEM', 'System')], max_length=20, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_requests', to='masters.branch')),
                ('gift_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_requests', to='masters.giftcycle')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_requests', to='shares.share')),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_requests', to='shareholders.shareholder')),
            ],
        ),
        migrations.CreateModel(
            name='GiftRequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('SHARE_CERTIFICATE', 'Share Certificate')], max_length=50)),
                ('original_file_name', models.CharField(max_length=255)),
                ('stored_file_name', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gift_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='gift_requests.giftrequest')),
            ],
        ),
        migrations.CreateModel(
            name='GiftRequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], max_length=20)),
                ('changed_by_type', models.CharField(choices=[('SHAREHOLDER', 'Shareholder'), ('STAFF', 'Staff'), ('ADMIN', 'Admin'), ('SYSTEM', 'System')], max_length=20)),
                ('changed_by_id', models.BigIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gift_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='gift_requests.giftrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RequestDeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('pincode', models.CharField(max_length=20)),
                ('is_from_master_address', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gift_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='gift_requests.giftrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='giftrequest',
            index=models.Index(fields=['request_no'], name='gift_reques_request_686a20_idx'),
        ),
        migrations.AddIndex(
            model_name='giftrequest',
            index=models.Index(fields=['mobile_number'], name='gift_reques_mobile__a79f63_idx'),
        ),
        migrations.AddIndex(
            model_name='giftrequest',
            index=models.Index(fields=['request_status'], name='gift_reques_request_186770_idx'),
        ),
        migrations.AddIndex(
            model_name='giftrequest',
            index=models.Index(fields=['branch'], name='gift_reques_branch__3b7e29_idx'),
        ),
        migrations.AddIndex(
            model_name='giftrequest',
            index=models.Index(fields=['gift_cycle'], name='gift_reques_gift_cy_9d245d_idx'),
        ),
    ]
