from django.urls import path
from .web_views import (
    staff_web_login,
    staff_web_logout,
    staff_dashboard,
    staff_request_list,
    staff_request_detail,
    staff_accept_request,
    staff_reject_request,
    staff_ship_request,
    staff_deliver_request,
    staff_document_download,
    staff_document_preview,
    staff_report_summary,
    staff_report_export_excel,
    staff_share_status_list,
    staff_share_status_update,
    staff_create_request_search,
    staff_create_request_form,
    staff_bulk_tracking_upload,
    staff_bulk_tracking_sample,
    staff_bulk_tracking_failed_export,
    staff_bulk_delivery_upload,
    staff_bulk_delivery_sample,
    staff_bulk_delivery_failed_export,
    staff_bulk_share_upload,
    staff_bulk_share_sample,
    staff_bulk_share_confirm_import,
    staff_bulk_share_upload_result,
    staff_bulk_share_failed_export,
    staff_bulk_share_status_upload,
    staff_bulk_share_status_sample,
    staff_bulk_share_status_failed_export,
)

urlpatterns = [
    path('login/', staff_web_login, name='staff-web-login'),
    path('logout/', staff_web_logout, name='staff-web-logout'),
    path('', staff_dashboard, name='staff-web-dashboard'),
    path('requests/', staff_request_list, name='staff-web-request-list'),
    path('requests/<int:gift_request_id>/', staff_request_detail, name='staff-web-request-detail'),
    path('requests/<int:gift_request_id>/accept/', staff_accept_request, name='staff-web-accept-request'),
    path('requests/<int:gift_request_id>/reject/', staff_reject_request, name='staff-web-reject-request'),
    path('requests/<int:gift_request_id>/ship/', staff_ship_request, name='staff-web-ship-request'),
    path('requests/<int:gift_request_id>/deliver/', staff_deliver_request, name='staff-web-deliver-request'),
    path('documents/<int:document_id>/download/', staff_document_download, name='staff-web-document-download'),
    path('documents/<int:document_id>/preview/', staff_document_preview, name='staff-web-document-preview'),
    path('reports/', staff_report_summary, name='staff-web-report-summary'),
    path('reports/export-excel/', staff_report_export_excel, name='staff-web-report-export-excel'),
    path('share-status/', staff_share_status_list, name='staff-web-share-status-list'),
    path('share-status/<int:share_id>/update/', staff_share_status_update, name='staff-web-share-status-update'),
    path('requests/create/', staff_create_request_search, name='staff-web-create-request-search'),
    path('requests/create/<int:share_id>/', staff_create_request_form, name='staff-web-create-request-form'),
    path('bulk/tracking/', staff_bulk_tracking_upload, name='staff-web-bulk-tracking-upload'),
    path('bulk/tracking/sample/', staff_bulk_tracking_sample, name='staff-web-bulk-tracking-sample'),
    path('bulk/tracking/failed-export/', staff_bulk_tracking_failed_export, name='staff-web-bulk-tracking-failed-export'),
    path('bulk/delivery/', staff_bulk_delivery_upload, name='staff-web-bulk-delivery-upload'),
    path('bulk/delivery/sample/', staff_bulk_delivery_sample, name='staff-web-bulk-delivery-sample'),
    path('bulk/delivery/failed-export/', staff_bulk_delivery_failed_export, name='staff-web-bulk-delivery-failed-export'),
    path('bulk/share-upload/', staff_bulk_share_upload, name='staff-web-bulk-share-upload'),
    path('bulk/share-upload/sample/', staff_bulk_share_sample, name='staff-web-bulk-share-sample'),
    path('bulk/share-upload/confirm/', staff_bulk_share_confirm_import, name='staff-web-bulk-share-confirm-import'),
    path('bulk/share-upload/result/', staff_bulk_share_upload_result, name='staff-web-bulk-share-upload-result'),
    path('bulk/share-upload/failed-export/', staff_bulk_share_failed_export, name='staff-web-bulk-share-failed-export'),
    path('bulk/share-status/', staff_bulk_share_status_upload, name='staff-web-bulk-share-status-upload'),
    path('bulk/share-status/sample/', staff_bulk_share_status_sample, name='staff-web-bulk-share-status-sample'),
    path('bulk/share-status/failed-export/', staff_bulk_share_status_failed_export, name='staff-web-bulk-share-status-failed-export'),
]