# Generated by Django 6.0.3 on 2026-04-09 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_requests', models.BooleanField(default=False)),
                ('can_create_request', models.BooleanField(default=False)),
                ('can_accept_request', models.BooleanField(default=False)),
                ('can_reject_request', models.BooleanField(default=False)),
                ('can_ship_request', models.BooleanField(default=False)),
                ('can_deliver_request', models.BooleanField(default=False)),
                ('can_bulk_tracking', models.BooleanField(default=False)),
                ('can_bulk_delivery', models.BooleanField(default=False)),
                ('can_bulk_share_upload', models.BooleanField(default=False)),
                ('can_bulk_share_status', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_roles', models.BooleanField(default=False)),
                ('can_manage_branches', models.BooleanField(default=False)),
                ('can_manage_share_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_permission', to='auth.group')),
            ],
        ),
    ]
