# Generated by Django 6.0.3 on 2026-04-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='can_reset_user_password',
            field=models.BooleanField(default=False),
        ),
    ]
