# Generated by Django 6.0.3 on 2026-04-06 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_code', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.TextField()),
                ('role_type', models.CharField(choices=[('BRANCH_STAFF', 'Branch Staff'), ('MULTI_BRANCH_STAFF', 'Multi Branch Staff'), ('MASTER_STAFF', 'Master Staff'), ('ADMIN', 'Admin')], max_length=30)),
                ('has_all_branch_access', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffBranchAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_accesses', to='masters.branch')),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_accesses', to='staffs.staffuser')),
            ],
            options={
                'unique_together': {('staff_user', 'branch')},
            },
        ),
    ]
